on:
  push:
    branches:
      - main
name: Deploy to test instance on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: Sync files
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
      with:
        ftp_host: ${{ secrets.ftp_server}}
        ftp_username: ${{ secrets.ftp_username}}
        ftp_password: ${{ secrets.ftp_password }}
        local_source_dir: "./"
        dist_target_dir: "./test.chungu.co.ke"
        delete: "false"
        exclude: "'^README.md' '^composer.lock' '^composer.json' '^.phpunit.result.cache' '^phpunit.xml' '^tests' '^.git/' '^static/assets for dev/'"        